server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:9296
  #cloud:
    #gateway:
      #routes:
        #- id : ORDER-SERVICE
          #uri: lb://ORDER-SERVICE
          #predicates:
            #- Path=/order/**
          #filters:
            #- name: CircuitBreaker
              #args:
                #name: ORDER-SERVICE
                #fallbackuri: forward:/orderServiceFallBack
            #- name: RequestRateLimiter
              #args:
                #redis-rate-limiter.replenishRate: 1
                #redis-rate-limiter.burstCapacity: 1



#okta:
  #oauth2:
    #issuer: https://dev-15585796.okta.com/oauth2/default
    #audience: api://default
    #client-id: 0oa6cgklvwIS2SoFZ5d7
    #client-secret: L_VPQB5XQX5QAhnxaDqA0IhWG-TImnVpaHW7ER33
    #scopes: openid, email, profile, offline_access